version: '3.9'

services:
  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    depends_on: 
      - db
    environment:
      pg_host: db
    ports:
      - "8003:8000"
    # network_mode: host
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.4"
    #       memory: "200MB"

  api2:
    <<: *api 
    hostname: api2
    ports:
      - "8002:8000"

  db:
    image: postgres:16-alpine
    volumes:
      - ./configs/db.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    # network_mode: host
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: "130MB"
    command: postgres -c max_connections=250

  nginx:
    image: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - api1
      - api2
    ports:
      - "9999:9999"
    # network_mode: host
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.2"
    #       memory: "20MB"
